dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: uP8hsn5mCCYOuLzykUWuq2gU7lfHDqKqJQsiYy+VKimtosJFDZCBgSOxf2aAqZrBBtofo2F4yMvaHsVmKUq6M3nu5wurbMqTMEg21fmHgDq0IoIUFQyrupo/JfJBD0m661mFzoD8e421t9/L1zA16DaSeRDAF8KPktIzkOgrhwvQWJK/TUdyoCSipr0+S/rBtKBiO6RqyR0NgTrpp8nSRYC5fHVrUq0umjpjYMDu4ILplPHbnS9zlXFz1rnvzmhBTBDijTTYtSS69e442IK93DIqzzM7+F9JF/kP4qkFT3I+jlM7mag0iQWloartQykHNeBYeqck62T1Q1fmxFFGyw2558RSU82qJRC2lF43e7aSBLEmBKWDK2U9t1e1MBFgTPxjjYYmN7Lo0ia7qxlxqJvOicMwI8vSEjbg9XnxNndxEeOlL+5TrfPwE90txj0nrlQx0czVTiVLkPM5bn7bI7Bxxmdwt3LgScml/4MPWUfmh1ha7W08OsGx04gu5xv7WWAJ0hDvU9wvbXbswIzaXZoER3pXef8Aqj3HJcynkrqEXHjfOXK/xeys5COSMN76XmTrxNlJEZmNGuKw7YIYCdT1E5vor6Ps88HkGB9nuxZC0h7nxreY45Lm1ZcLIX9fXoUYtdtPCL6leFOBLpyjKu+Z2JDSXUTPGH5cgOUUtyg=
